// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// read_plink_cpp
SEXP read_plink_cpp(std::string bedfile, std::string famfile, int impute, bool verbose);
RcppExport SEXP _plinkR_read_plink_cpp(SEXP bedfileSEXP, SEXP famfileSEXP, SEXP imputeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bedfile(bedfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type famfile(famfileSEXP);
    Rcpp::traits::input_parameter< int >::type impute(imputeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(read_plink_cpp(bedfile, famfile, impute, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plinkR_read_plink_cpp", (DL_FUNC) &_plinkR_read_plink_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_plinkR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
