# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_plink_cpp <- function(bedfile, famfile, impute, verbose) {
    .Call(`_plinkR_read_plink_cpp`, bedfile, famfile, impute, verbose)
}

